name: Sync Fork

on:
  schedule:
    # Programa esto para que se ejecute una vez al día a la medianoche
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Permite ejecutar este flujo de trabajo manualmente desde GitHub Actions

jobs:
  sync:
    runs-on: ubuntu-20.04

    steps:
    # Check out the fork's repository
    - name: Checkout Fork
      uses: actions/checkout@v4.1.7
      with:
        # Recoge el historial completo para poder hacer los merge correctamente
        fetch-depth: 0

    # Configura el repositorio original como 'upstream'
    - name: Setup Upstream
      run: |
        git remote add upstream https://github.com/Maure-dev/Trabajo-Prog-III.git
        git fetch upstream

    # Fusiona los cambios de 'upstream/main' en 'main'
    - name: Merge Upstream Changes
      run: |
        git checkout dev
        git merge upstream/dev

    # Envía los cambios al fork en GitHub
    - name: Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin dev
